export default [
  {
    Version: 1,
    Key: '226396',
    Type: 'City',
    Rank: 10,
    LocalizedName: 'Tokyo',
    EnglishName: 'Tokyo',
    PrimaryPostalCode: '',
    Region: {
      ID: 'ASI',
      LocalizedName: 'Asia',
      EnglishName: 'Asia',
    },
    Country: {
      ID: 'JP',
      LocalizedName: 'Japan',
      EnglishName: 'Japan',
    },
    AdministrativeArea: {
      ID: '13',
      LocalizedName: 'Tokyo',
      EnglishName: 'Tokyo',
      Level: 1,
      LocalizedType: 'Prefecture',
      EnglishType: 'Prefecture',
      CountryID: 'JP',
    },
    TimeZone: {
      Code: 'JST',
      Name: 'Asia/Tokyo',
      GmtOffset: 9,
      IsDaylightSaving: false,
      NextOffsetChange: null,
    },
    GeoPosition: {
      Latitude: 35.683,
      Longitude: 139.809,
      Elevation: {
        Metric: {
          Value: 1,
          Unit: 'm',
          UnitType: 5,
        },
        Imperial: {
          Value: 3,
          Unit: 'ft',
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [],
    DataSets: [
      'AirQualityCurrentConditions',
      'AirQualityForecasts',
      'Alerts',
      'ForecastConfidence',
      'FutureRadar',
      'MinuteCast',
      'Radar',
    ],
  },
  {
    Version: 1,
    Key: '623',
    Type: 'City',
    Rank: 20,
    LocalizedName: 'Paris',
    EnglishName: 'Paris',
    PrimaryPostalCode: '',
    Region: {
      ID: 'EUR',
      LocalizedName: 'Europe',
      EnglishName: 'Europe',
    },
    Country: {
      ID: 'FR',
      LocalizedName: 'France',
      EnglishName: 'France',
    },
    AdministrativeArea: {
      ID: '75',
      LocalizedName: 'Ville de Paris',
      EnglishName: 'Ville de Paris',
      Level: 1,
      LocalizedType: 'Department',
      EnglishType: 'Department',
      CountryID: 'FR',
    },
    TimeZone: {
      Code: 'CEST',
      Name: 'Europe/Paris',
      GmtOffset: 2,
      IsDaylightSaving: true,
      NextOffsetChange: '2022-10-30T01:00:00Z',
    },
    GeoPosition: {
      Latitude: 48.857,
      Longitude: 2.351,
      Elevation: {
        Metric: {
          Value: 35,
          Unit: 'm',
          UnitType: 5,
        },
        Imperial: {
          Value: 114,
          Unit: 'ft',
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: 'Paris',
        EnglishName: 'Paris',
      },
    ],
    DataSets: [
      'AirQualityCurrentConditions',
      'AirQualityForecasts',
      'Alerts',
      'DailyPollenForecast',
      'ForecastConfidence',
      'FutureRadar',
      'MinuteCast',
      'Radar',
    ],
  },
  {
    Version: 1,
    Key: '349727',
    Type: 'City',
    Rank: 15,
    LocalizedName: 'New York',
    EnglishName: 'New York',
    PrimaryPostalCode: '10021',
    Region: {
      ID: 'NAM',
      LocalizedName: 'North America',
      EnglishName: 'North America',
    },
    Country: {
      ID: 'US',
      LocalizedName: 'United States',
      EnglishName: 'United States',
    },
    AdministrativeArea: {
      ID: 'NY',
      LocalizedName: 'New York',
      EnglishName: 'New York',
      Level: 1,
      LocalizedType: 'State',
      EnglishType: 'State',
      CountryID: 'US',
    },
    TimeZone: {
      Code: 'EDT',
      Name: 'America/New_York',
      GmtOffset: -4,
      IsDaylightSaving: true,
      NextOffsetChange: '2022-11-06T06:00:00Z',
    },
    GeoPosition: {
      Latitude: 40.779,
      Longitude: -73.969,
      Elevation: {
        Metric: {
          Value: 8,
          Unit: 'm',
          UnitType: 5,
        },
        Imperial: {
          Value: 26,
          Unit: 'ft',
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: 'New York',
        EnglishName: 'New York',
      },
    ],
    DataSets: [
      'AirQualityCurrentConditions',
      'AirQualityForecasts',
      'Alerts',
      'DailyAirQualityForecast',
      'DailyPollenForecast',
      'ForecastConfidence',
      'FutureRadar',
      'MinuteCast',
      'Radar',
    ],
  },
  {
    Version: 1,
    Key: '178087',
    Type: 'City',
    Rank: 10,
    LocalizedName: 'Berlin',
    EnglishName: 'Berlin',
    PrimaryPostalCode: '10178',
    Region: {
      ID: 'EUR',
      LocalizedName: 'Europe',
      EnglishName: 'Europe',
    },
    Country: {
      ID: 'DE',
      LocalizedName: 'Germany',
      EnglishName: 'Germany',
    },
    AdministrativeArea: {
      ID: 'BE',
      LocalizedName: 'Berlin',
      EnglishName: 'Berlin',
      Level: 1,
      LocalizedType: 'State',
      EnglishType: 'State',
      CountryID: 'DE',
    },
    TimeZone: {
      Code: 'CEST',
      Name: 'Europe/Berlin',
      GmtOffset: 2,
      IsDaylightSaving: true,
      NextOffsetChange: '2022-10-30T01:00:00Z',
    },
    GeoPosition: {
      Latitude: 52.518,
      Longitude: 13.406,
      Elevation: {
        Metric: {
          Value: 35,
          Unit: 'm',
          UnitType: 5,
        },
        Imperial: {
          Value: 114,
          Unit: 'ft',
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 2,
        LocalizedName: 'Berlin',
        EnglishName: 'Berlin',
      },
    ],
    DataSets: [
      'AirQualityCurrentConditions',
      'AirQualityForecasts',
      'Alerts',
      'DailyPollenForecast',
      'ForecastConfidence',
      'FutureRadar',
      'MinuteCast',
      'Radar',
    ],
  },
  {
    Version: 1,
    Key: '308526',
    Type: 'City',
    Rank: 10,
    LocalizedName: 'Madrid',
    EnglishName: 'Madrid',
    PrimaryPostalCode: '',
    Region: {
      ID: 'EUR',
      LocalizedName: 'Europe',
      EnglishName: 'Europe',
    },
    Country: {
      ID: 'ES',
      LocalizedName: 'Spain',
      EnglishName: 'Spain',
    },
    AdministrativeArea: {
      ID: 'MD',
      LocalizedName: 'Madrid',
      EnglishName: 'Madrid',
      Level: 1,
      LocalizedType: 'Autonomous Community',
      EnglishType: 'Autonomous Community',
      CountryID: 'ES',
    },
    TimeZone: {
      Code: 'CEST',
      Name: 'Europe/Madrid',
      GmtOffset: 2,
      IsDaylightSaving: true,
      NextOffsetChange: '2022-10-30T01:00:00Z',
    },
    GeoPosition: {
      Latitude: 40.41,
      Longitude: -3.686,
      Elevation: {
        Metric: {
          Value: 639,
          Unit: 'm',
          UnitType: 5,
        },
        Imperial: {
          Value: 2095,
          Unit: 'ft',
          UnitType: 0,
        },
      },
    },
    IsAlias: false,
    SupplementalAdminAreas: [
      {
        Level: 3,
        LocalizedName: 'Madrid',
        EnglishName: 'Madrid',
      },
    ],
    DataSets: [
      'AirQualityCurrentConditions',
      'AirQualityForecasts',
      'Alerts',
      'DailyPollenForecast',
      'ForecastConfidence',
      'FutureRadar',
      'MinuteCast',
      'Radar',
    ],
  },
];
